### ISSUE TITLE
Error when running application

### ISSUE THREAD

**Issue by experion-anumol** [richbl/ang2-visualizejs#2]
While running the application I am stuck with the error "ERROR Error: Uncaught (in promise): ReferenceError: visualize is not defined". I think there is some issue with visualize function in drawResource function. Could someone please help me out?

**Comment by richbl** [comment]
Running this project on Ubuntu 17.04 (node v4.7.2, npm v3.5.2), I cannot reproduce the error you describe.

What OS and node/npm versions are you running?

**Comment by experion-anumol** [comment]
I'm using a Windows 8 system with node 7.9.0 and npm 4.2.0

**Comment by richbl** [comment]
I don't run Windows, so you may need to do some Googling to identify the cause. Also, check out http://community.jaspersoft.com/, as there have been similar reports indicated of this "visualize is not defined" issue when running Windows.
