### ISSUE TITLE
How can i Build Code

### ISSUE THREAD

**Issue by krishnaUI** [richbl/ang2-visualizejs#3]
I want to build the code and deploy in tomcat. please let me know. How can i do it.

**Comment by richbl** [comment]
We've never had a need to deploy Angular to a Tomcat Server.

I'd suggest Googling for ng2 and Tomcat. Here are some results: 

- https://stackoverflow.com/questions/40852931/how-can-i-deploy-an-angular-2-application-on-tomcat-server-windows-server-2012
- https://stackoverflow.com/questions/39018765/deploy-angular-2-app-with-webpack-to-tomcat-404-errors/44727035#44727035
